### ISSUE TITLE
Guarantee data coherence for key DAOs treasuries

### ISSUE THREAD

**Issue by lajarre** [butterdao/whip#77]
```yaml
primedao: 0x567d220B0169836cBF351DF70A9c517096ec9De7
bankless: 0xf26d1bb347a59f6c283c53156519cc1b1abaca51
gitcoin:
    timelock: 0x57a8865cfB1eCEf7253c27da6B4BC3dAEE5Be518
    multisig: 0xde21F729137C5Af1b01d73aF1dC21eFfa2B8a0d6
    treasuryvester: 0x44aa9c5a034c1499ec27906e2d427b704b567ffe
radicle: 0x8da8f82d2bbdd896822de723f55d6edf416130ba
ens:
    registrar: 0x283Af0B28c62C092C9727F1Ee09c02CA627EB7F5
    proxy: 0xCF60916b6CB4753f58533808fA610FcbD4098Ec0
    timelock: 0xFe89cc7aBB2C4183683ab71653C4cdc9B02D44b7
    tokenlock: 0xd7A029Db2585553978190dB5E85eC724Aa4dF23f
nouns: 0x0BC3807Ec262cB779b38D65b38158acC3bfedE10
bitdao: 0x78605Df79524164911C144801f41e9811B7DB73D
uniswap:
    unitimelock: 0x1a9c8182c09f50c8318d769245bea52c32be35bc
    treasuryvester1: 0x4750c43867ef5f89869132eccf19b9b6c4286e1a
    treasuryvester2: 0xe3953d9d317b834592ab58ab2c7a6ad22b54075d
    treasuryvester3: 0x4b4e140d1f131fdad6fb59c13af796fd194e4135
    treasuryvester4: 0x3d30b1ab88d487b0f3061f40de76845bec3f1e94
gnosis:
    1: 0x458cD345B4C05e8DF39d0A07220feb4Ec19F5e6f
    2: 0x10E4597fF93cbee194F4879f8f1d54a370DB6969
    gnosissafeproxy: 0x4971DD016127F390a3EF6b956Ff944d0E2e1e462
    gnosisdaosafe: 0x0DA0C3e52C977Ed3cBc641fF02DD271c3ED55aFe
    instaaccountv2: 0xfa5dcf356a2d80cf0c89d64a18a742edaf8d30e8
    activetreasurymanagement: 0x849D52316331967b6fF1198e5E32A0eB168D039d
    proxy: 0xbc79855178842fdba0c353494895deef509e26bb
    vesting: 0xec83f750adfe0e52a8b0dba6eeb6be5ba0bee535
balancer:
    multisig: 0x10A19e7eE7d7F8a52822f6817de8ea18204F2e4f
    protocolfeescollector: 0xce88686553686DA562CE7Cea497CE749DA109f9F
```
